### ISSUE TITLE
Addtion of granule segmentation method to SunPy

### ISSUE THREAD

**Issue by LDZuckerman** [sunpy/sunkit-image#107]
We are a group of students working on a project to segment granules in solar images, which will allow researchers to identify locations of rising convective cells and intergranular lanes. We intend that our granule segmentation method could be applied to DKIST or other high-resolution images of the solar photosphere. We are hoping that our code may be useful to other researchers, and thus may be a beneficial addition to SunPy (most likely Sunkit-Image). We spoke with Stuart Mumford a few weeks ago, who suggested opening an issue as a first step, and then sharing our code by opening a pull request. Stuart mentioned it could be good to do this as soon as we had some initial code, however, before sharing code we wanted to open an issue to address the following: 

- Our method is built on top of existing lower level Python packages (e.g from skimage). Would this be considered for potential integration with SunPy?

- We have assumed the best input and output formats would be SunPy “maps”, as they appear to be the main data format in SunPy. Would another format be preferred? 

- What types of testing would the SunPy developers like to see in our final product?

Thank you so much for your time

**Comment by LDZuckerman** [comment]
Hello, 
Just to clarify - you would like us to create a branch of the sunkit-image repo containing the functionality we have created, and then initiate a pull-request to the main branch?

**Comment by nabobalis** [comment]
> Hello, Just to clarify - you would like us to create a branch of the sunkit-image repo containing the functionality we have created, and then initiate a pull-request to the main branch?

I would suggest you fork the sunkit-image repo (there should be a fork button near the top right).
Then you can add your new functionality, then you can initiate a pull-request to this repo.
