### ISSUE TITLE
`mgn` docstring is incomplete

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunkit-image#117]
The docstring for the `mgn` function should include a note that the data array should be already normalized by the exposure time. This has the effect of converting the data to floating point type as well which is necessary for this function. See [this discourse post](https://community.openastronomy.org/t/error-running-multiscale-gaussian-normalization-code/558) for more information.

**Comment by Saksham-13** [comment]
hey @wtbarnes, I fixed the issue and opened a pull request #126, however, it seems that I am unaware of the contribution guidelines as some tests have failed, can you guide me toward the necessary guidelines that  I need to follow

**Comment by nabobalis** [comment]
> hey @wtbarnes, I fixed the issue and opened a pull request #126, however, it seems that I am unaware of the contribution guidelines as some tests have failed, can you guide me toward the necessary guidelines that I need to follow

Please do not @ people unless you need them. 

I will review your PR later today.

**Comment by Saksham-13** [comment]
Apologies, I will keep that in mind going forward
