### ISSUE TITLE
Clean up `sunkit_image.trace` API

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunkit-image#134]
### Provide a general description of the issue or problem.

The [`sunkit_image.trace` ](https://docs.sunpy.org/projects/sunkit-image/en/latest/code_ref/trace.html)API has several functions that we could make private, as they're only used in the `occult2` loop tracing algorithm. 

I think we should leave only these functions as public facing API:
- `occult2`
- `bandpass_filter` (and move this submodule?)
- `smooth` (and move this to another submodule?)

**Comment by nabobalis** [comment]
Sure

**Comment by Saksham-13** [comment]
Hey, I would like to work on this issue, can I be assigned to it ?

**Comment by Saksham-13** [comment]
I did not understand the moving to another submodule part completely, can it be elaborated on?

**Comment by nabobalis** [comment]
I assume and @dstansby will correct me, is that he suggests we move those functions out of the file and into a utils or other part of the library.

**Comment by dstansby** [comment]
I suggest we make them private by putting an underscore ("_") in front of their name, and just leave them where they are. A clear changelog entry also will need writing to explain which functions have been changed.

**Comment by Saksham-13** [comment]
A little more clarification @dstansby 

> I suggest we make them private by putting an underscore ("_") in front of their name, and just leave them where they are. A clear changelog entry also will need writing to explain which functions have been changed.

A bit of confusion for me,are you referring to the `bandpass_filter` and `smooth` functions too or just the other ones which should be private?

**Comment by dstansby** [comment]
The ones *not* listed in the original post above should be made private

**Comment by Pardheevsai03** [comment]
hello, can I know why this issue is still open? the functions are made private already. I can try to solve this issue if there is still something to do.

**Comment by nabobalis** [comment]
Yes I forgot to close this issue when we merged that PR. Sorry about that.

**Comment by rachelle-hc** [comment]
If this issue is completed then is it removed from the gsoc list of issues to be solved under the "Improve sunkit-image" idea for gsoc this year? These are pre-tasks for that idea project or part of that project?


> Yes I forgot to close this issue when we merged that PR. Sorry about that.

If this issue is completed then is it removed from the gsoc list of issues to be solved under the "Improve sunkit-image" idea for gsoc this year? These are pre-tasks for that idea project or part of that project? I see that the issue was closed on Feb 9, which does come under gsoc this year, so I am just a little confused about this..

**Comment by nabobalis** [comment]
> If this issue is completed then is it removed from the gsoc list of issues to be solved under the "Improve sunkit-image" idea for gsoc this year? These are pre-tasks for that idea project or part of that project? I see that the issue was closed on Feb 9, which does come under gsoc this year, so I am just a little confused about this..

Yes, if I left that issue on the GSoC project than its just an oversight. You can leave it from your proposal.
