### ISSUE TITLE
We are missing dependencies from the install_requires and relying on them through other packages

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunkit-image#159]
### Describe the bug

The conda-forge bot reckons we need:

-    matplotlib
-    extension-helpers
-    scipy
-    astropy
-    numpy

Some of them might be doc only, but numpy certainly feels like it's missing.

**Comment by nabobalis** [comment]
Yeah I was lazy, since we use sunpy, I didn't add those directly.

I will change this.
