### ISSUE TITLE
Rename the package for imports

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-image#16]
We should come up with a better shorter name like `scikit-image` which is `skimage`. 

Currently we have `sunkit_image`.

**Comment by Cadair** [comment]
What is it at the moment?

**Comment by nabobalis** [comment]
`sunkit_image`

**Comment by wafels** [comment]
spimage ?

**Comment by MinaSGorgy** [comment]
snimage?

**Comment by Cadair** [comment]
Personally I would either stick with `sunkit_image` or go with `sunimage` I think the name has to actually have some meaning to it, i.e. include the full words `sun` and `image`

**Comment by corleone7476** [comment]
A better short name for this would be spy_image because it includes focus on python in the part 'spy' and 'image' is important because it is a toolkit for image processing

**Comment by nabobalis** [comment]
Could we even be more bold and drop the entire sunkit bit? I don't think we need to copy the titling of scikits (even if i was for it way back when).

**Comment by corleone7476** [comment]
But since the library is to be developed for sunpy(Solar Physics) image processing, hence it might be reasonable to include some mention of sunpy in the title.

**Comment by nabobalis** [comment]
I will close this and leave the name as is. We can come back to this in the future.
