### ISSUE TITLE
De-Class NoiseLevelEstimation

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-image#18]
### Description

When #12 is merged in, I propose turning `NoiseLevelEstimation` into a series of functions and not a class.

**Comment by MSKirk** [comment]
I agree on this front. There are several noise level estimation routines that are appropriate for use in solar images. I think a series of functions would better represent these.

**Comment by m-squared96** [comment]
Hey, just a heads up. I'm a GSoC hopeful and I'm attempting to fix this issue. Currently WIP. I have the original NoiseLevelEstimation object "de-classed" and now I just need to test to make sure functionality has remained the same.

**Comment by dpshelio** [comment]
I would take a different approach. I would have a denoise class and different functions as different strategies, that is how the strategy pattern works. This is the implementation on a [solar physics example](http://github-pages.ucl.ac.uk/rsd-engineeringcourse/ch05construction/09patterns.html#Strategy-Pattern).

**Comment by nabobalis** [comment]
So we just refactor the class to enable someone to add more functions?
