### ISSUE TITLE
Use coord tracing code in the trace example to return the loop intensities 

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-image#198]
In that case, we should expand the tracing example to:

"I think we should just use the coord tracing stuff we have in sunpy to show how once you have the SkyCoord you can extract the intensities a la https://docs.sunpy.org/en/stable/generated/gallery/units_and_coordinates/map_slit_extraction.html#sphx-glr-generated-gallery-units-and-coordinates-map-slit-extraction-py"

**Comment by Abinash-bit** [comment]
Hi @nabobalis can you please clear , what do "coord tracing stuff we have in sunpy" means or can you provide the link of how to have the SkyCoord any codebase !!

**Comment by nabobalis** [comment]
Hello @Abinash-bit,

https://docs.sunpy.org/en/stable/generated/gallery/units_and_coordinates/map_slit_extraction.html#sphx-glr-generated-gallery-units-and-coordinates-map-slit-extraction-py is what is meant by the "coord tracing stuff we have in sunpy". That would allow the example to be extended to pull the values from the data array out at the end. 

I am not sure if we produce a skycoord out at the end of the example, I forget now.
