### ISSUE TITLE
Interactive region drawing on maps

### ISSUE THREAD

**Issue by wafels** [sunpy/sunkit-image#2]
It is often useful to interactively select a region on an image using a mouse.  For example, a user might want to outline a particular region in an image, extract that region only, or integrate the emission in that region.  Sunkit-image should supply the capability to interactively select a region and return the co-ordinates of the selected region.

**Comment by prateekiiest** [comment]
will it be same as part of the Region of Interest Project?

**Comment by wafels** [comment]
Maybe the connection should be that the result of the interactive region
drawing would be a region of interest object.

**Comment by nabobalis** [comment]
I'm gonna close this for now since I think this should probably be a feature of the `Region of Interest Project`. If it doesn't belong in sunpy, we can move it when the code exists.
