### ISSUE TITLE
Remove `calculate_solar_rotate_shift` and `mapsequence_coalign_by_rotation`

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunkit-image#203]
### Provide a general description of the issue or problem.

These methods are not needed and are just worse versions of functionality we already have in `sunpy` to reproject images given some model of differential rotation, e.g. https://docs.sunpy.org/en/stable/generated/gallery/differential_rotation/reprojected_map.html#sphx-glr-generated-gallery-differential-rotation-reprojected-map-py

**Comment by Deus1704** [comment]
This issue too can be marked complete since the #206 has been merged.
