### ISSUE TITLE
Implement the Radial Histogram Equalizing Filter

### ISSUE THREAD

**Issue by GillySpace27** [sunpy/sunkit-image#204]
### Describe the feature

I would like to contribute one of the results of my thesis work (found at [https://www.proquest.com/docview/2759080511](https://www.proquest.com/docview/2759080511)) called the Radial Histogram Equalizing Filter. It is a hybrid adaptive histogram equalizing filter and radial graded filter, and would live in the Radial module or the Enhancement module.

### Proposed solution

I have already forked the repo and implemented the algorithm and a test for it, but now it just needs more tests and probably some stylistic changes.

**Comment by GillySpace27** [comment]
I believe that this code is present in the main branch now. When can we expect it to turn up in pypi?

Thanks!

**Comment by nabobalis** [comment]
My hope is currently November. I want to get out the new coalignment PR merged in before a new release. But that can come later. I will have to decide later this month.
