### ISSUE TITLE
One of these functions is not like the others

### ISSUE THREAD

**Issue by GillySpace27** [sunpy/sunkit-image#220]
Basically, in the `sunkit-image.radial` module, the exported functions are all "full, stand-alone" algorithms except for the "set attenuation coefficients" function, which is just a helper for the FNRGF algorithm. 

`__all__ = ["fnrgf", "intensity_enhance", "set_attenuation_coefficients", "nrgf", "rhef"]

I would suggest that the parameters could just be passed in as arguments to the main algorithm, rather than having an extra public function. Could also be handled by importing from the utils file, for ease of understanding. 

https://github.com/sunpy/sunkit-image/blob/f7df5023d1b1a97b2433ae8439083058d041158d/sunkit_image/radial.py#L13-L18

```[tasklist]
### Tasks
```

**Comment by nabobalis** [comment]
Yeah, that is good idea!

**Comment by Abinash-bit** [comment]
#243 fixes this.

**Comment by Abinash-bit** [comment]
@nabobalis @GillySpace27
