### ISSUE TITLE
Usage of non-AIA images in radial.rhef is broken

### ISSUE THREAD

**Issue by GillySpace27** [sunpy/sunkit-image#233]
### Describe the bug

When using different data sources, radial.rhef doesn't always know how to find the center of the image and do the units correctly. I've opened a draft PR #231 that I think might fix the problem but I'm open to some testing and iteration by others. In general I need to generalize the algorithm to be as agnostic to data source as possible. Thanks for your help!

### To Reproduce

```python
from sunpy.map import Map
from sunkit_image.radial import rhef
import matplotlib.pyplot as plt
import os

for file in os.listdir("example_data/"):
    if "fits" in file:
        target = os.path.join("example_data", file)
        pmap = Map(target)[0]
        pmap_filt = rhef(pmap)
        plt.figure()
        pmap_filt.plot()
        plt.savefig(target.replace(".fits", ".png"))
```

### Screenshots

Output is nonsense:
![image](https://github.com/user-attachments/assets/8b333932-36d5-421a-aea6-1dc4baeb9115)

### System Details

```
>>> import sunpy; sunpy.util.system_info()
==============================
sunpy Installation Information
==============================

General
#######
OS: Mac OS 14.5
Arch: 64bit, (arm)
sunpy: 6.0.2
Installation path: /Users/cgilbert/vscode/punch-5-meeting/.venv/lib/python3.12/site-packages/sunpy-6.0.2.dist-info

Required Dependencies
#####################
astropy: 6.1.3
numpy: 1.26.4
packaging: 24.1
parfive: 2.1.0
pyerfa: 2.0.1.4
requests: 2.32.3

Optional Dependencies
#####################
sunpy: 6.0.2
```

### Installation method

git checkout

**Comment by nabobalis** [comment]
What was the data you used in that example? We need to consider adding more test data from not-AIA.

**Comment by Abinash-bit** [comment]
> ### Describe the bug
> When using different data sources, radial.rhef doesn't always know how to find the center of the image and do the units correctly. I've opened a draft PR #231 that I think might fix the problem but I'm open to some testing and iteration by others. In general I need to generalize the algorithm to be as agnostic to data source as possible. Thanks for your help!
> 
> ### To Reproduce
> ```python
> from sunpy.map import Map
> from sunkit_image.radial import rhef
> import matplotlib.pyplot as plt
> import os
> 
> for file in os.listdir("example_data/"):
>     if "fits" in file:
>         target = os.path.join("example_data", file)
>         pmap = Map(target)[0]
>         pmap_filt = rhef(pmap)
>         plt.figure()
>         pmap_filt.plot()
>         plt.savefig(target.replace(".fits", ".png"))
> ```
> 
> ### Screenshots
> Output is nonsense: ![image](https://private-user-images.githubusercontent.com/11935569/369989971-8b333932-36d5-421a-aea6-1dc4baeb9115.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjU2NTUsIm5iZiI6MTczMTMyNTM1NSwicGF0aCI6Ii8xMTkzNTU2OS8zNjk5ODk5NzEtOGIzMzM5MzItMzZkNS00MjFhLWFlYTYtMWRjNGJhZWI5MTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExNDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDRjNDY5NTVmODNmZTRkZjYzMmI4MzQwZjczZmFiYTMxNzA2ZmMyYzc2YzlmOWRjNTJlYTMwMDIzM2Q5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A1ao5HBaRlgXkAXDeXQsWl1OYO9qB2yoxlEEgGwntXo)
> 
> ### System Details
> ```
> >>> import sunpy; sunpy.util.system_info()
> ==============================
> sunpy Installation Information
> ==============================
> 
> General
> #######
> OS: Mac OS 14.5
> Arch: 64bit, (arm)
> sunpy: 6.0.2
> Installation path: /Users/cgilbert/vscode/punch-5-meeting/.venv/lib/python3.12/site-packages/sunpy-6.0.2.dist-info
> 
> Required Dependencies
> #####################
> astropy: 6.1.3
> numpy: 1.26.4
> packaging: 24.1
> parfive: 2.1.0
> pyerfa: 2.0.1.4
> requests: 2.32.3
> 
> Optional Dependencies
> #####################
> sunpy: 6.0.2
> ```
> 
> ### Installation method
> git checkout



Seems like i can not reproduce the issue ....

can anyone help me with this?

this is what i get when i try to reproduce!!

![Screenshot 2024-11-11 173015](https://github.com/user-attachments/assets/e8d10a14-65f7-4a08-a710-d0cd0d4744a9)

**Comment by nabobalis** [comment]
This issue was fixed by https://github.com/sunpy/sunkit-image/pull/231 and I forgot to close this PR. 

In your case, the code example, uses data on the original authors laptop.
