### ISSUE TITLE
Enable enhanced Ruff linting

### ISSUE THREAD

**Issue by CyclingNinja** [sunpy/sunkit-image#241]
As part of the ongoing efforts to align The SunPy Community's package infrastructure across all sub packages, we are moving all repos to the same linting and formatting rule set.

In order to update the repo the following steps need to be taken.

1.. Update the `use_extended_ruff_linting` variable from `n` to `y` (you will need cruft installed)
```shell
$ cruft update --variables-to-update '{"use_extended_ruff_linting": "y"}'
```

2. Locally format your code using `tox -e codestyle` 

3. You can use `ruff check --unsafe-fixes` cli tool to correct a great deal of the formatting with minimal interruption

4. Fix the remaining linting or formatting.

5. PR :tada:

**Comment by Abinash-bit** [comment]
Hey @CyclingNinja can you say where i can find ``use_extended_ruff_linting`` variable , like in which file of the sunkit-image?

**Comment by nabobalis** [comment]
That line is in https://github.com/sunpy/sunkit-image/blob/main/.cruft.json#L19
