### ISSUE TITLE
Clicking on a method, the background box is in the wrong location. 

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-image#27]
When I click on weektexturemask, this happened. 
![screenshot from 2019-03-03 16-49-28](https://user-images.githubusercontent.com/1392107/53698423-5b8f7480-3dd4-11e9-9a15-fcd54fa2f33e.png)

The background box in the incorrect location.

**Comment by Cadair** [comment]
I think I have seen this in other places?

**Comment by nabobalis** [comment]
I couldn't replicate it on GenericMap when I was testing for it.
