### ISSUE TITLE
Normalizing-radial-graded filter (NRGF)

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-image#3]
The idea is found [here](http://adsabs.harvard.edu/abs/2006SoPh..236..263M).

The method is:

![screenshot from 2018-02-23 10-24-14](https://user-images.githubusercontent.com/1392107/36587049-2bb7c5da-1884-11e8-8aba-f94fae35d64f.png)

We have a "working"  version currently in `offlimb_enhance.py`.

Base:
- [ ] Working and well implemented algorithm. 
- [ ] Compared to known output/example for verification. 

Extra:
- [ ] Optimized as much as possible for memory and CPU time.
- [ ] 100% test coverage and numerical tests. 
- [ ] Documentation and a worked example.
- [ ] Go through two IDL versions to see if we are missing anything from our version. [IDL version 1](https://hesperia.gsfc.nasa.gov/ssw/packages/nrl/idl/nrlgen/display/nrgf.pro), [IDL version 2](http://www.heliodocs.com/php/xdoc_print.php?file=$SSW/packages/corimp/idl/nrgf_corimp.pro). For the first one we are aware that this implementation includes a *lot* more extra stuff which is not described in the paper like looking for bad pixels before doing the processing.  Functionality like this should be separated and ideally added as generalized functions in `util.py`.

**Comment by prateekiiest** [comment]
@nabobalis , in our case will we be normalizing the map data using this method?

Int that case,  what will be the height and the angle?

The [paper](https://arxiv.org/pdf/astro-ph/0602174.pdf) says about this.

**`I'(r,theta) = (I(r,theta) - mean(r,theta))/sigma(r,theta)`**

What will be r, theta in AIA data, or is it some other data we wish to apply this method on?

**Comment by nabobalis** [comment]
From the paper, `r` is height, `theta` is position angle. They should be using polar coordinates over cartesian coordinates

**Comment by prateekiiest** [comment]
oh!! , polar coordinates.

So instead of using the normal coordinates as of now, we need to first convert this into polar coordinates and then apply this, or implement in the cartesian coordinates directly ?

**Comment by nabobalis** [comment]
Well we get an input which is an array. You'd probably have to work out how the equation can be applied in a cartesian way.

**Comment by prateekiiest** [comment]
ok in an abstract sense, something like this maybe

`norm_data =( aiamap.data - aiamap.data.mean() )/ pow(np.var(aiamap.data),0.5)`

**Comment by nabobalis** [comment]
I suspect that your interpretation of the equation is incorrect.

**Comment by nabobalis** [comment]
I will have to check the paper to refresh my memory.

**Comment by prateekiiest** [comment]
ok, I will reread the paper, then

**Comment by nabobalis** [comment]
There is an IDL version of the [code here.](https://hesperia.gsfc.nasa.gov/ssw/packages/nrl/idl/nrlgen/display/nrgf.pro)

**Comment by wafels** [comment]
I have a bunch of code in my master branch of sunkit-image, including the
NRGF filter - see
https://github.com/wafels/sunkit-image/blob/master/sunkit_image/offlimb_enhance.py#L275
.

The file
https://github.com/wafels/sunkit-image/blob/master/sunkit_image/offlimb_enhance.py
expands the concepts behind this gallery example of the offlimb enhancement
<https://github.com/sunpy/sunpy/blob/master/examples/off_limb_enhance.py> .
I think it needs to be broken down a bit more to be more generally useful.
For example, finding which pixels are off or on limb in a map is a
generally useful function that could be expanded to consider an arbitrary
radial distance instead of being fixed at the solar radius.  This would
allow us to use the same function for coronagraph images too.

Anyway, I could PR this code in to sunkit-image, and then others could fork
it.  How about that?

**Comment by nabobalis** [comment]
Sure.

**Comment by prateekiiest** [comment]
Thanks for the links to the codes @wafels @nabobalis .
I will look into and will let you know if any queries

**Comment by prateekiiest** [comment]
should we use `ctypes` or `cython` in our python code implementation for this for faster execution?

**Comment by nabobalis** [comment]
I would like to avoid it if possible.

**Comment by prateekiiest** [comment]
any suggestions on how we can achieve better performance compared to IDL?

**Comment by nabobalis** [comment]
Worry about that once we have a working code that has tests.

**Comment by prateekiiest** [comment]
so should I mention ways in which we can work on achieving better performance in my application?

**Comment by nabobalis** [comment]
Yes that's fine.

**Comment by himanshukgp** [comment]
![figure_2](https://user-images.githubusercontent.com/22715286/37228491-d5bf0894-2406-11e8-9008-f35082214be8.png)
Implementing @wafels code gives this.

**Comment by wafels** [comment]
The color stretching needs to be changed to get a better view of the
results.  Let me try this too.  Thanks!

**Comment by himanshukgp** [comment]
Are we going to convert it to Grayscale ?

**Comment by wafels** [comment]
I tried the code.  The map output uses a LinearStretch, is limited to the range [-2,2] and uses the matplotlib RdBu colormap

![figure_1](https://user-images.githubusercontent.com/983575/37230854-d35a2890-23b6-11e8-9046-d0073d54939e.png)

**Comment by wafels** [comment]
I think this looks reasonable.  It would be nice to try this on a LASCO image, maybe even a LASCO JP2 image.

**Comment by wafels** [comment]
Actually, you can see the effect of the radial bins... I wonder if there is a way to smooth this out?

**Comment by himanshukgp** [comment]
@wafels How did you change the colour stretching above ? Will increasing the number of bins make it smoother ?

**Comment by maykillmore** [comment]
Sir I'd like to take up this issue if no one is currently doing it.

**Comment by nabobalis** [comment]
I am not aware that anyone is working on this issue but we try not to assign issues to people. 

You are free to do any issue.

**Comment by vatch123** [comment]
I think this issue was also solved with #17
