### ISSUE TITLE
Increase test coverage sunkit-image

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-image#33]
We need to be aware of our test coverage and with #40 it will drop.

So rising this back as high as possible is important.

Missing direct tests:
- `fit_polynomial_to_log_radial_intensity`
- `normalize_fit_radial_intensity`
- `calculate_fit_radial_intensity`
- `intensity_enhance`
- `calc_gamma`
- `remove_duplicate`
- `points_in_poly`
- `reform2d`
- `Lamb_Oseen`

**Comment by jeffreypaul15** [comment]
How exactly would the tests be verified? Would I have to manually calculate (based on how the function performs the calculation) the values and then check if the required functions return the same value?

**Comment by nabobalis** [comment]
Sounds like a plan.
