### ISSUE TITLE
Declass ASDA

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-image#42]
When pull request #40 is merged in, it would be worthwhile to declass the code into a series of functions.

**Comment by jeffreypaul15** [comment]
is this still a requirement?

**Comment by nabobalis** [comment]
Yes.

**Comment by jeffreypaul15** [comment]
> Yes.

Could I give this a go?

**Comment by nabobalis** [comment]
Sure.

**Comment by jeffreypaul15** [comment]
> Sure.

How would the init methods be replaced though? For example, would every function requiring the `vx` variable need passing of this variable?

**Comment by nabobalis** [comment]
Not sure, I've not really looked at the class in a long time. I guess that would need to be figured out in the process of declassing it. 

Maybe it isn't worth it.

**Comment by jeffreypaul15** [comment]
> Not sure, I've not really looked at the class in a long time. I guess that would need to be figured out in the process of declassing it.
> 
> Maybe it isn't worth it.

I'll make a PR regarding this and then maybe you can decide based on that?

**Comment by nabobalis** [comment]
Probably be less time if you just have a play with it and see how it goes rather than doing a full PR. If it seems just be a headache, we can just close this issue.

**Comment by jeffreypaul15** [comment]
Every method in the `Asda` class needs the attribures that are initialized, if we declass it we'll have to pass all these variables to the methods individually. Is it worth doing this?

**Comment by nabobalis** [comment]
No probably not.

**Comment by Telomelonia** [comment]
@nabobalis 
Are the classes to be removed after making the functions out of classes?

**Comment by nabobalis** [comment]
> @nabobalis Are the classes to be removed after making the functions out of classes?

At the same time?

**Comment by Telomelonia** [comment]
> > @nabobalis Are the classes to be removed after making the functions out of classes?
> 
> At the same time?

No .. no actually I was thinking that declass meant to completely remove the class but now it is ok I have defined the function separately

**Comment by nabobalis** [comment]
> > > @nabobalis Are the classes to be removed after making the functions out of classes?
> > 
> > 
> > At the same time?
> 
> No .. no actually I was thinking that declass meant to completely remove the class but now it is ok I have defined the function separately

What is the reason to define it separately and keep the class?

**Comment by Telomelonia** [comment]
I'm just being cautious as I noticed the `ASDA` class was inherited in the `Lamb_Oseen` class [here](https://github.com/sunpy/sunkit-image/blob/62907383ce3c889100cef35d87063c7a27b74250/sunkit_image/asda.py#L258)... so at first, I felt this inheritance reduces a lot of parameters in the functions.  And so, I would like to discuss this before removing the classes.

**Comment by Ghaithq** [comment]
can I work on this? @nabobalis

**Comment by nabobalis** [comment]
Sure.

**Comment by 010100100100011101010100** [comment]
@nabobalis I will really glad to work and contribute from my side. It is wrong on my part to not understand the issue completely, could you kindly provide some assistance?

**Comment by nabobalis** [comment]
> @nabobalis I will really glad to work and contribute from my side. It is wrong on my part to not understand the issue completely, could you kindly provide some assistance?

Hello @010100100100011101010100, currently this issue is being worked on by @Ghaithq. If you want to help, you can ask them otherwise I would suggest another issue.

**Comment by rachelle-hc** [comment]
> > @nabobalis I will really glad to work and contribute from my side. It is wrong on my part to not understand the issue completely, could you kindly provide some assistance?
> 
> Hello @010100100100011101010100, currently this issue is being worked on by @Ghaithq. If you want to help, you can ask them otherwise I would suggest another issue.

@Ghaithq , Could you please explain the issue once clearly? I cannot find the issue specified anywhere?

**Comment by nabobalis** [comment]
> > > @nabobalis I will really glad to work and contribute from my side. It is wrong on my part to not understand the issue completely, could you kindly provide some assistance?
> > 
> > 
> > Hello @010100100100011101010100, currently this issue is being worked on by @Ghaithq. If you want to help, you can ask them otherwise I would suggest another issue.
> 
> @Ghaithq , Could you please explain the issue once clearly? I cannot find the issue specified anywhere?

Hello @rachelle-hc, do you mean the open pull request addressing this issue? If so that is here: https://github.com/sunpy/sunkit-image/pull/185 

Or would you like a actual concrete issue description? I relassise that I opened this issue with 0 details but I never came back to improve on it.

**Comment by nabobalis** [comment]
Closed by #185
