### ISSUE TITLE
Add link to docs on github home page

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunkit-image#63]
Could someone who has edit access on github add the documentation link ( https://docs.sunpy.org/projects/sunkit-image/en/stable/) to the github front page (https://github.com/sunpy/sunkit-image)? This is where I usually look for documentation links, and I don't think it's there at the moment.

**Comment by nabobalis** [comment]
Done.

**Comment by nabobalis** [comment]
Added it to the readme as well.
