### ISSUE TITLE
Inconsistent input types across functions

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunkit-image#69]
Most functions in this package accept the image as a bare numpy array. However, a few (e.g. `radial.fnrgf`) take a `sunpy.map.GenericMap` as an input.

It would be convenient to always accept and return a `Map`. However, this is not always practical, e.g. in the `time_lag.cross_correlation` function, it is useful to be able to provide everything from 1D timeseries to 3D image cubes to the function, none of which can be contained in a `Map` object at the moment. 

I think, in general, it would be useful to accept either a map or a bare array (e.g. using something like `singledispatch`) unless it is not practical to accept a `Map` at all (e.g. in the time lag case).

**Comment by wafels** [comment]
The original idea was to have the algorithms operate on bare numpy arrays only. It insulates the image processing from changes to the `Map` object. I think this approach is still appropriate.

**Comment by Cadair** [comment]
I think we should be providing map (or ndcube) aware functions for as many cases as possible, even if there are underlying functions which are implementations of things just targeting a numpy array?

**Comment by wafels** [comment]
I am sure the community would like the convenience of passing in a `Map` or some higher level object. Some of the existing algorithms may need to be re-implemented to separate out the base algorithm.

**Comment by Saksham-13** [comment]
Hey, I would like to work on this issue, can you point out any function which would be easy to convert than others so I can start working on it, Thanks.

**Comment by nabobalis** [comment]
This issue is related to the GSoC project, as such we won't be allowing work on this for now.
