### ISSUE TITLE
OCCULT-2 algorithm

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-image#9]
The original idea comes [from here](https://arxiv.org/abs/1307.5046).

A [tutorial](http://www.lmsal.com/~aschwand/software/tracing/tracing_tutorial1.html) and the [latest code](https://hesperia.gsfc.nasa.gov/ssw/packages/mjastereo/idl/looptracing_auto4.pro)

We need to figure out which of those IDL codes is the true method or what the difference is between them.

We think that `tracing_auto` calls `tracing_direction` and `tracing_step` while `tracing_auto2` is a modified version of `tracing_auto` which uses both a high pass and low pass filter. However this would need to be checked. 

Base:
- [ ] Working and well implemented algorithm. 
- [ ] Numerically compared to known working output (as a test).

Extra:
- [ ] Optimized as much as possible for memory and CPU time.
- [ ] 100% test coverage
- [ ] Documentation and a worked example.

**Comment by prateekiiest** [comment]
The IDL code does not implement the low pass filter, I suppose

**Comment by nabobalis** [comment]
Well first would be to figure out which of those IDL codes is the true method or what the difference is between them.

**Comment by prateekiiest** [comment]
[Tracing_Auto][https://hesperia.gsfc.nasa.gov/ssw/packages/mjastereo/idl/tracing_auto.pro], I believe is the main code which calls [Tracing Direction](https://hesperia.gsfc.nasa.gov/ssw/packages/mjastereo/idl/tracing_direction.pro) and [Tracing Step](https://hesperia.gsfc.nasa.gov/ssw/packages/mjastereo/idl/tracing_step.pro)  within it.

Although Tracing Direction is not actually called as I saw through the code in Tracing_Auto, but its still commented that way.

Tracing_auto2 is the modified of tracing auto I presume, which uses both high pass and low pass , but I dont know why has commented in that section as `HIGHPASS FILTER`

**Comment by prateekiiest** [comment]
Tracing Auto 2
![screenshot 49](https://user-images.githubusercontent.com/16035442/36633102-6e7cfa0c-19b5-11e8-968a-b11f8b8688fe.png)
