### ISSUE TITLE
Failing test `test_multiscale_gaussian`

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunkit-image#96]
### Describe the bug

`test_multiscale_gaussian` is failing sometimes on the CI.

I have been unable to replicate any of the fails locally using tox, changing Python version etc.

I have marked it as `xfail` for now but we need to debug this, see https://github.com/sunpy/sunkit-image/pull/95/

### To Reproduce

I can't.

**Comment by meghana151** [comment]
Hello, Can I work on this?

**Comment by nabobalis** [comment]
Sure.

**Comment by Deus1704** [comment]
I have tested by removing the @pytest.mark.xfail for the `test_multiscale_gaussian` with the python versions: 3.9, 3.10, 3.11 and their corresponding oldest dependencies too and all of them pass.

I believe that this issue can be safely closed.

**Comment by nabobalis** [comment]
Can you pull request the removal of the mark? Only if it passes on the ci, will we remove this

**Comment by Deus1704** [comment]
sure!
